server:
  port: 80

eureka:
  instance:
    instance-id: 80-hystrix-order
    prefer-ip-address: true
  client:
    # 是否要注册到Eureka,默认是true
    register-with-eureka: true
    # 是否从Eureka Server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置feign客户端超时时间（feign默认支持ribbon）
ribbon:
  # 指的是连接建立后，从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true