server:
  port: 80

eureka:
  instance:
    instance-id: 80-order
    prefer-ip-address: true
  client:
    # 是否要注册到Eureka,默认是true
    register-with-eureka: false
    # 是否从Eureka Server抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka